version: "3.9"

services:

  db:
    image: ankane/pgvector
    container_name: pgvector_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dharma
      POSTGRES_DB: ai_tutor
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: ai_tutor_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:dharma@db:5432/supernowa_ai
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
